version: '3.8'

services:
  syndic-app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: syndicpro_app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # Persistance hermétique des bases de données SQLite (Air-Gap)
      - ../data:/var/www/html/Syndic/data
      # Persistance des médias et logos téléversés
      - ../uploads:/var/www/html/Syndic/uploads
    environment:
      - TZ=Africa/Casablanca
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/Syndic/"]
      interval: 30s
      timeout: 10s
      retries: 3
